# Generated by Django 4.2.4 on 2023-08-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no_from", models.TextField()),
                ("gist", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="userquery",
            name="gist",
            field=models.TextField(default="none"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userquery",
            name="phone_no_from",
            field=models.TextField(default=919999999999),
            preserve_default=False,
        ),
    ]
