# Generated by Django 4.2.3 on 2023-08-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquery",
            name="phone_no_from",
            field=models.TextField(default=917990565567),
            preserve_default=False,
        ),
    ]
