# Generated by Django 4.2.4 on 2023-08-31 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_usergist_userquery_gist_userquery_phone_no_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergist",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userquery",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
