# Generated by Django 4.2.3 on 2023-08-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_userquery_phone_no_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no_from", models.TextField()),
                ("gist", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="userquery",
            name="gist",
            field=models.TextField(default="nothing"),
            preserve_default=False,
        ),
    ]
