# Generated by Django 4.2.4 on 2023-09-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_usergist_created_at_userquery_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquery",
            name="message_count",
            field=models.IntegerField(default=1),
        ),
    ]
