# Generated by Django 4.2.3 on 2023-08-31 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_usergist_userquery_gist"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergist",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userquery",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
