# Generated by Django 4.2.3 on 2023-08-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_usergist_created_at_userquery_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcmeWebhookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(help_text="When we received the event."),
                ),
                ("payload", models.JSONField(default=None, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["received_at"], name="bot_acmeweb_receive_1ee1a7_idx"
                    )
                ],
            },
        ),
    ]
