# Generated by Django 4.2.4 on 2023-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_userquery_message_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquery",
            name="profile_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userquery",
            name="phone_no_from",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
