# Generated by Django 4.2.4 on 2023-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_userquery_profile_name_alter_userquery_phone_no_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquery",
            name="response_message_segregation",
            field=models.TextField(default="none"),
            preserve_default=False,
        ),
    ]
