# Generated by Django 4.2.4 on 2023-09-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_userquery_response_message_segregation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquery",
            name="id",
        ),
        migrations.AddField(
            model_name="userquery",
            name="message_internal_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
