# Generated by Django 4.2.3 on 2023-11-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_remove_userquery_id_userquery_message_internal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergist",
            name="currentstate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userquery",
            name="currentstate",
            field=models.IntegerField(default=0),
        ),
    ]
